README.md
examples/advanced.rs
examples/basic.rs
examples/multiple_viewports.rs
examples/multiple_viewports_windows.rs
examples/multiple_windows.rs
src/lib.rs

Makes it work with multiple viewports and windows, rather than hard coding the primary window.
Orbiting rotation amount is calculated from the window size, rather than the viewport. I did this as using viewport size for rotation meant that small viewports had much too high sensitivity. That's because the amount of rotation is 360 degrees if you go edge to edge. For small viewports, that physical distance may be very small.
Panning is calculated from the viewport size, as it needs to be 1:1 with the mouse.
Demos:
https://user-images.githubusercontent.com/7709415/234175395-1b148e89-a68e-43d1-82cb-644f40bb5874.mp4
https://user-images.githubusercontent.com/7709415/234175427-8fe3cdf6-f34c-47d6-8225-fa3ab0d4bd21.mp4

Add multiple viewport/window support

---

README.md
examples/animate.rs
src/lib.rs

* Adds `orbit_smoothness` option so you can change how smooth the orbiting motion is
* Fixes bug that meant you could only programmatically update the camera's position if it was the 'active' camera. This meant that a) you had to click once before it would work, and b) you could only control one camera at a time.
* Add `animate` example which demos how to animate the camera's motion
* Minor renaming and comment fixing

Add orbit_smoothness option, fix bug, and add animation example

---

README.md
examples/animate.rs
examples/keyboard_controls.rs
src/lib.rs

Some of this was already possible, but there were a couple issues:
* Constraints (upside down, and min/max alpha/beta) only applied to mouse input. Fixed by always applying these constraints.
* Modifying radius on its own didn't do anything. Fixed by adding a `force_update` option which forces recalculation of rotation and translation. This also technically applied to the focus, but since you only notice where the focus is when you rotate, it didn't make any difference.
* It wasn't possible to zoom orthographic cameras by setting radius, so I had to change it so the orthographic projection's scale is based off the radius.
Adds keyboard control example.

Add ability to control camera manually (e.g. with keyboard)

---

Cargo.toml
examples/keyboard_controls.rs
src/lib.rs

Fixes regression introduced in 0.4.0, where the camera would stop when you let go of the mouse.

Keep processing if target alpha/beta is not the same as current

---

src/lib.rs

Fixes #14 
I found that when the exit condition was set to `OnPrimaryClosed`, as soon as the run condition returned false, the `check_egui_wants_focus` system stopped executing. I can see how this makes sense, because the system was set to run before `PanOrbitCameraSystemSet` which is now not running. But I am not sure if that's actually how Bevy works. Additionally, it _does_ run regardless if `OnAllClosed` exit condition is used. Whatever the cause may be, using a base set instead works as expected. Base sets are also the only example of system sets I can find in the official examples, which may hint at something...

Convert system set to base set to fix bug with egui feature

---

Cargo.toml
README.md
examples/advanced.rs
examples/animate.rs
examples/basic.rs
examples/egui.rs
examples/keyboard_controls.rs
examples/multiple_viewports.rs
examples/multiple_windows.rs
src/lib.rs
src/util.rs

This revamps how we initialize. Use camera position to calculate initial alpha, beta, and radius, if they aren't set. If they are, override camera's position instead.
This also removes the (actually broken, I realised) constructor method `from_translation_and_focus` that creates an instance from a transform, since it is now redundant.
This includes some other minor improvements to documentation and various small cleanup things.
Thanks to https://github.com/Plonq/bevy_panorbit_camera/pull/4 for the idea of this change.

Revamped, more flexible initialization code

---

examples/advanced.rs
examples/orthographic.rs
src/lib.rs
src/util.rs

Adds zoom limiting, which will apply to radius or scale, depending on the camera's projection.
Credit goes to @mrivnak for the idea and part of the implementation in [their PR](https://github.com/Plonq/bevy_panorbit_camera/pull/26) - thanks!

Add zoom limiting

---

examples/manual_override.rs
examples/render_to_texture.rs
src/lib.rs

Adds ability to manage `ActiveCameraData` resource manually, which allows one to control cameras that don't render to a viewport (render to texture), or just generally allows forcing input from one window/viewport to be used for a specific camera.
This does not support multiple cameras that are controlled from different windows/viewports. The only way to have multiple cameras be controllable is to let the plugin handle `ActiveCameraData`.
Fixes #33

Render to texture support

---

examples/touch/Cargo.lock
src/input.rs
src/lib.rs
src/util.rs

Reorganises input-related code into `input` mod, to simplify the main system. This is a step towards separating out the orbit/pan/zoom logic from everything else, which may allow supporting an alternate implementation in the future. But even if that doesn't happen it's still an improvement to the overall code structure. There's more to do, but this is a good start.
Oh also this includes an update to the touch example's cargo lock file, for no reason other than I can't be bothered separating that change 😆

Refactor input code

---

README.md
examples/advanced.rs
examples/alternate_up_vector.rs
examples/basic.rs
examples/orthographic.rs
examples/render_to_texture.rs
examples/touch/src/lib.rs
src/input.rs
src/lib.rs
src/traits.rs
src/util.rs

closes #41 
Adds the ability to control the 3rd rotational axis (roll), in addition to yaw/tilt (alpha/beta). Adding the 3rd axis can make things weird, in that it changes what the camera treats as 'up' (the up vector). And once the up vector has changed, it's practically impossible to reset it back to default with just the camera controls. You have to reset it programmatically. For this reason, roll is disabled by default in both mouse/kb controls and touch controls.
Also, the concept of being 'upside down' makes no sense when you can change what 'up' means, and so `allow_upside_down` should typically be set to `true` when enabling roll or changing the up vector.
The roll control is implemented by introducing a 'base transform' upon which all other transformations are applied. By …

Add 'roll' controls and custom 'up' vector support

---

examples/advanced.rs
src/input.rs
src/lib.rs

Fixes #46 
Makes the 'roll' controls framerate independent.
Also fixes bug where you have to click once before rolling worked.
https://github.com/Plonq/bevy_panorbit_camera/issues/48 is still a problem but will deal with that separately.

Framerate independence for 'roll' controls

---

examples/advanced.rs
examples/roll_axis.rs
examples/touch/Cargo.lock
examples/touch/src/lib.rs
src/input.rs
src/lib.rs

Closes #48 
As explained in #48, having built-in roll controls has issues. First, having keyboard-only controls is ambiguous where there are multiple cameras - which one to control? Secondly, unlike orbit/pan, there are no obvious/intuitive roll controls. Rolling by moving the mouse feels weird, and using keyboard is a bit clunky and not as precise.
Additionally, rolling the camera is most likely a very uncommon use case, because it modifies the up vector which can result in weird perspectives and confusion. It is also practically impossible to get the up vector back to the world 'up' with just the camera controls themselves - you have to manually reset it.
For these reasons, I've decided to remove the built-in roll controls, and let anyone that wants to roll the camera do so if they …

Remove built-in roll controls

---

.github/workflows/main.yml

Try to arrange for most efficiency. `cargo build` is slower than `cargo check` but some errors only emit when generating the code, so I run `cargo build` (and thus don't need to run `cargo check`).
Also no need to check tests if it runs the tests anyway.

GH Actions changes

---

examples/orthographic.rs
src/lib.rs
src/util.rs

I've added an example of switch projection to the orthographic example
https://github.com/Plonq/bevy_panorbit_camera/assets/35809384/8e9dc3fc-e9f0-4549-9cb6-63fbedac039c

Remove `scale` field from `PanOrbitCamera`

---

examples/orthographic.rs

Switching from orthographic to perspective sometimes causes a flicker (1 frame by the looks of it). Not 100% reproducible, but I believe the problem is caused when the projection changes after PanOrbitCameraSystemSet runs, so I've updated the example to always switch before it runs.

Fix flicker in orthographic example

---

src/lib.rs
src/util.rs

Makes the smoothing frame rate independent. The defaults have to change, as the scaling of values between 0 and 1 has changed. The new scale makes more sense, but 0 is still 'disabled' and 1 is still 'infinite' smoothing.

Frame rate independent smoothing

---

src/lib.rs

Fixes #65 
I had incorrectly assumed that if a `Camera` was referencing a window as its target, that that window would always exist. However, it seems that if there are multiple windows and one window is closed, the camera rendering to that window is not automatically removed and thus refers to a window that no longer exists.
I've updated the code to handle this case - instead of panicking with `expect` I just skip that camera.

Fix crash when one of multiple windows is closed

---

README.md
examples/advanced.rs
examples/animate.rs
examples/keyboard_controls.rs
src/lib.rs
src/util.rs

Due to popular demand, I'm renaming alpha to yaw and beta to pitch, to be more intuitive, even if not _entirely_ accurate.
Closes #68

Rename alpha to yaw and beta to pitch

---

src/lib.rs

When egui feature enabled, instead of not running any of the orbit cam systems when egui 'wants focus', only skip getting input from the user. This fixes the camera stopping moving instantly if you hover over an egui window and release the the mouse buttons).
Fixes #71 
https://github.com/Plonq/bevy_panorbit_camera/assets/7709415/4878ddc3-c88d-40a8-8e3d-6cdbfa32abc7

71 movement stops if mouse over egui

---

Cargo.toml

I really wanted to be able to use copy and paste again. 🙂

Bump `bevy_egui` version to 0.27

---

examples/egui.rs
src/egui.rs
src/lib.rs

Implements an optional and imperfect workaround for https://github.com/Plonq/bevy_panorbit_camera/issues/75
To use the workaround:
```rust
// Insert this resource
.insert_resource(EguiFocusIncludesHover(true))
// Before this plugin
.add_plugins(PanOrbitCameraPlugin)
```
The reason it is imperfect is that moving the mouse over any egui panel will block all input from panorbit camera, even if you are already dragging (e.g. to rotate).
I've also moved the panorbit systems into `PostUpdate` to avoid potential race conditions depending on how systems are scheduled.

Implement workaround for egui issue with panels

---

examples/egui.rs
src/lib.rs

- When starting to orbit, this continue to work even when the pointer move to over a egui window/area
- When the mouse click and drag operation start in an egui window/area the camera does not start to orbit when getting out of the area and in the viewport

Fix egui focus edge cases

---

Cargo.toml

resolves a compatibility issue with:
`bevy-inspector-egui = "0.27"`

fix: update to latest bevy_egui

---

examples/focus_bounds.rs
src/lib.rs

A hack I made to add bounds to the camera when panning. If this is something you'd consider implementing please let me know, support for different shaped boundaries would be nice to have, this is just a starting point

Add bounds to Focus in line with other movement options

---

Cargo.toml

This PR upgrades the `bevy_egui` dependency to the latest released version of `bevy_egui` (`0.33.0`)

Upgrade bevy_egui to 0.33

---

.gitignore
examples/swapped_axis.rs
src/input.rs
src/lib.rs
src/util.rs

Hi,
this is a first version the ability to swap axis. The reason is that Bevy treats +Y as default up axis. However this does not align with some standard frames that are used e.g. in astrodynamics. There the default up direction is usually +Z. Also see https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/Tutorials/pdf/individual_docs/17_frames_and_coordinate_systems.pdf .
In this case all the objects would have to be rotated which is very inconvenient. A common use case it to have the center at the earth and use the J2000 frame. For having the earth at the center and just orbiting around bevy_panorbit_camera is perfect if this change is considered.
Please let me know what you think. I already tested it manually in my project and it works nicely. Also I added a few small tests following your …

Axis swapping first version

---

src/lib.rs

**Motivation:**
In my use case it is more intuitive to keep the default rotation and not invert it if the camera is below the default orbital plane as you would never usually really want to "invert the camera", but just "see it from below". See also the gif.
**Change:**
Introduced an attribute to control whether the orbiting direction is inverted if the camera is below the default presentation plane.
What do you think?

Disable orbiting direction inversion if camera is below default presentation plane.

---

src/lib.rs

Reverts Plonq/bevy_panorbit_camera#106

Revert "Disable orbiting direction inversion if camera is below default presentation plane."

---

Cargo.toml

Bumping the dependency version compiled without warnings or errors.
<details>
<summary>
cargo test --features bevy_egui:
</summary>
```                                                                                                                                                                       
Running unittests src\lib.rs (target\debug\deps\bevy_panorbit_camera-a139ba134503c8f9.exe)
running 18 tests
test util::approx_equal_tests::same_value_is_approx_equal ... ok
test util::approx_equal_tests::value_outside_threshold_is_not_approx_equal ... ok
test util::approx_equal_tests::value_within_threshold_is_approx_equal ... ok
test util::calculate_from_translation_and_focus_tests::above ... ok
test util::calculate_from_translation_and_focus_tests::above_z_as_up_axis ... ok
test …
```

bump bevy_egui to 0.36
